title: Joseph Boyd
# description: Much-Worse Jekyll theme for academic page and blog
# sourcecode: "https://github.com/gchauras/much-worse-jekyll-theme"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://jcboyd.github.io"     # the base hostname & protocol for your site

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
highlighter: rouge
